### PR TITLE
Use `NoTangent()` instead of `nothing` to designate non-differentiability

### PR DESCRIPTION
**Pull request by mzgubic**
Needed so that https://github.com/JuliaDiff/FiniteDifferences.jl/pull/189 does not break ChainRules tests

### CODE REVIEW

**Review by AlexRobson — COMMENTED** [review]
This is changing the length of the return - i.e. from (nothing, nothing...) to  a single `NoTangent()`. Is this intended? 

I'm surprised no tests had to change to handle this. 

I think that this means that [here](https://github.com/JuliaDiff/ChainRulesTestUtils.jl/blob/master/src/testers.jl#L224) given that the output of `fd_cotangents`) will only be length one, the zip will only loop over the first argument.

**Comment by mzgubic** [comment]
well caught, that's a mistake

**Review by willtebbutt — APPROVED** [review]
I have no objection to this going in, but like @AlexRobson I'm a bit surprised that there's no changes needed to the tests. Do we just not have great coverage in this package?

**Comment by mzgubic** [comment]
I think the reason is that this is an implementation detail. It is not visible anywhere outside of the package.

**Pull request merged**
