### PR TITLE
Implement isapprox for Composites

### PR DESCRIPTION
**Pull request by willtebbutt**
What it says on the tin.

### CODE REVIEW

**Review by mzgubic — APPROVED** [review]

**Comment by willtebbutt** [comment]
Thanks for approving @mzgubic . Should I be worried about the integration test failure?

**Comment by mzgubic** [comment]
> Thanks for approving @mzgubic . Should I be worried about the integration test failure?

I have seen it on a few recent PRs but could not reproduce this failure on my machine. Perhaps we should investigate? It seems like there is something wrong with CI but this is not really my area of expertise.

**Comment by willtebbutt** [comment]
Ah okay. Maybe open an issue about it? I'll merge this in the mean time.

**Comment by mzgubic** [comment]
will do

**Pull request merged**
